# Generated by Django 3.2.4 on 2023-05-16 03:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filmwork",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="",
                        verbose_name="Path to file",
                    ),
                ),
                (
                    "imdb_rating",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="IMDB Rating",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("serial", "Serial"),
                            ("cartoon", "Cartoon"),
                            ("tv_show", "TV show"),
                        ],
                        default="movie",
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "access_level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Access level"
                    ),
                ),
            ],
            options={
                "verbose_name": "Filmwork",
                "verbose_name_plural": "Filmworks",
                "db_table": 'content"."filmwork',
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "db_table": 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full name"),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
                "db_table": 'content"."person',
            },
        ),
        migrations.CreateModel(
            name="FilmworkPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Role"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "filmwork",
                    models.ForeignKey(
                        db_column="filmwork_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.filmwork",
                        verbose_name="Filmwork",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.person",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "FilmworkPerson",
                "verbose_name_plural": "FilmworkPersons",
                "db_table": 'content"."filmwork_person',
            },
        ),
        migrations.CreateModel(
            name="FilmworkGenre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "filmwork",
                    models.ForeignKey(
                        db_column="filmwork_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.filmwork",
                        verbose_name="Filmwork",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        db_column="genre_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.genre",
                        verbose_name="Genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "FilmworkGenre",
                "verbose_name_plural": "FilmworkGenres",
                "db_table": 'content"."filmwork_genre',
            },
        ),
        migrations.AddField(
            model_name="filmwork",
            name="genres",
            field=models.ManyToManyField(
                through="src.FilmworkGenre", to="src.Genre", verbose_name="Genres"
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                through="src.FilmworkPerson", to="src.Person", verbose_name="Persons"
            ),
        ),
        migrations.AddIndex(
            model_name="filmworkperson",
            index=models.Index(
                fields=["filmwork", "person", "role"],
                name="filmwork_pe_filmwor_425cc8_idx",
            ),
        ),
    ]
