@startuml
autonumber
footer Page %page% of %lastpage%
participant Users_Service
participant User
participant bd_историяРассылок
participant API
participant Admin_panel
participant Queue
participant Рассылка_По_Виду



== Отправка рассылки по команде администратора(срочная рассылка) ==
User->Admin_panel: Создает рассылку.обязательные поля. Вид рассылки. Шаблон сообщения.
Admin_panel->User: Сообщаем что рассылка создана
Admin_panel->API: Пользователь по нажатию кнопки отправляет в API
API->Queue: Отравляет данные по виду рассылки поля id Рассылки, id вида рассылки, проверка часового пояса
Queue->Рассылка_По_Виду: Данные из очереди отпрляются в блок
Рассылка_По_Виду->Users_Service: Отправляем данные с id вида рассылки
Users_Service->Рассылка_По_Виду: Получаем данные для шаблона для каждого пользователя который подписан на этот вид рассылки
Рассылка_По_Виду->bd_историяРассылок: По каждому пользователю пишем запись в базу данных
bd_историяРассылок->Рассылка_По_Виду: Данные записаны
alt Если у вида рассылки есть реквизит проверять на актуальность
    Рассылка_По_Виду->ПроверкаДанных: проверяет Время отправки
else Ревизит значение отрицательное
    Рассылка_По_Виду->db: записывает что сообщения не отправлены по причине не актуальности события
end


@enduml
