# Generated by Django 4.2.3 on 2023-08-01 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('LOGIN', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('DOMAIN', models.CharField(max_length=50)),
                ('SMTP_HOST', models.CharField(max_length=50)),
                ('SMTP_PORT', models.CharField(max_length=4)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail_template', models.FileField(default='', upload_to='templates')),
                ('time_control', models.BooleanField(default=True)),
                ('data_control', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='System_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_name', models.CharField(max_length=200)),
                ('id_events', models.UUIDField()),
                ('mailing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing_type')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('primary', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('sent_out', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('mail_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.mail_account')),
                ('mailing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing_type')),
            ],
        ),
    ]
