# Generated by Django 4.2.3 on 2023-08-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=2000)),
                ('created', models.DateField(auto_now_add=True)),
                ('mail_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.mailing_list')),
            ],
        ),
    ]
