# Generated by Django 4.2.3 on 2023-08-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_list_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_data',
            name='name',
            field=models.CharField(choices=[('title', 'title'), ('text', 'text'), ('image', 'image')], max_length=50),
        ),
    ]
