# Generated by Django 4.2.3 on 2023-08-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_data_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_events',
            name='id_events',
        ),
    ]
