# Generated by Django 4.2.3 on 2023-08-02 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_system_events_id_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing_list',
            name='day_send',
            field=models.CharField(choices=[('monday', 'Monday')], default='monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing_list',
            name='dispatch_time_hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing_list',
            name='send_time_minute',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing_list',
            name='single_mailing',
            field=models.BooleanField(default=False),
        ),
    ]
