# Generated by Django 4.2.3 on 2023-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_mailing_list_day_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_list',
            name='day_send',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
    ]
