# Generated by Django 4.2.3 on 2023-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_list_day_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_list',
            name='day_send',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='monday', max_length=10),
        ),
    ]
