# Generated by Django 4.2.3 on 2023-08-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_list_day_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PushServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SmsOperators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='mail_account',
            old_name='DOMAIN',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='mail_account',
            old_name='LOGIN',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='mail_account',
            old_name='PASSWORD',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='mail_account',
            old_name='SMTP_HOST',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='mail_account',
            old_name='SMTP_PORT',
            new_name='smtp_port',
        ),
        migrations.AddField(
            model_name='mail_account',
            name='sender',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail_account',
            name='smtp_host',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing_type',
            name='agent',
            field=models.CharField(choices=[('mail', 'mail'), ('web_push', 'web_push'), ('sms', 'sms'), ('messenger', 'messenger')], default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WebPushList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mailing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing_type')),
                ('push_services', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.pushservices')),
            ],
        ),
        migrations.CreateModel(
            name='SmsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mailing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing_type')),
                ('sms_operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.smsoperators')),
            ],
        ),
        migrations.CreateModel(
            name='Messenger_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mailing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing_type')),
                ('messenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.messengers')),
            ],
        ),
    ]
