# Generated by Django 4.2.3 on 2023-08-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_messengers_pushservices_smsoperators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing_list',
            name='last_sent_time',
            field=models.DateField(default=None, null=True),
        ),
    ]
