# Generated by Django 4.2.3 on 2023-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailing_list_last_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_list',
            name='last_sent_time',
            field=models.DateField(default=None, null=True),
        ),
    ]
