@startuml
autonumber
footer Page %page% of %lastpage%
participant service
participant api
participant django_db

== Обработка промокода полученного от стороннего сервиса ==
service->api: передает промо код, запрашивая по нему данные через get запрос.
api->django_db: Получаем данные по промо коду и блокируем его если он есть.
alt промо код корректный
    django_db->api: возвращаем информацию по промо коду
    api->service: переедаем данные из промокода
    service->api: Информацию о совершении или нет сделки
    api->django_db: в зависимости от результата операции записываем данные в таблицу Discount_History, промо код снимаем блокировку
else промо код корректный(просроченный или уже использовался если он разовый)
    django_db->api: возвращает информацию что код уже использовался или просрочен.
end

@enduml
