@startuml
autonumber
footer Page %page% of %lastpage%
participant user
participant fastapi_app
participant es_movie
queue data_buffer
participant kafka
queue cache_movie


== get film data ==
user->fastapi_app:  запрашивает информацию о фильме передаем токен
fastapi_app->fastapi_app: Проверяем токен
fastapi_app->es_movie:  запрашивает информацию о фильме
es_movie->fastapi_app:  Отправляет информацию о кино
es_movie-x data_buffer:  Отправляет информацию о запросе в буфер данных
alt Данные удачно добавлены в kafka
    data_buffer-> kafka:  Отправляет информацию о запросе в хранилище данных
    kafka-> data_buffer:  Ответ что данные записаны успешно
else сервис kafka не доступен
    data_buffer-> kafka:  Отправляет информацию о запросе в хранилище данных
end
'es_movie-x kafka:  Отправляет информацию о запросе в хранилище данных
fastapi_app-x cache_movie: Добавляем фильмы в кеш
fastapi_app->user:  возвращаем информацию о кино




@enduml
